### ISSUE TITLE
Consider replacing uglify in build process with Closure Compiler

### ISSUE THREAD

**Issue by robbear** [elix/elix#1]
The use of Closure may give us better minification along with lint analysis. Look at the pipeline in gulp/tasks/browserify.js.

**Comment by victornpb** [comment]
I used it in a project and gave me good results. Advanced mode also do dead code removal and function inlining, but some times it require some tweaks in the code. But simple compression is pretty reliable

**Comment by robbear** [comment]
Thanks for the feedback, @victornpb!

**Comment by robbear** [comment]
Closing as no longer relevant. Elix will ship ES6, and build issues belong exclusively to the consumer of the package.
