### ISSUE TITLE
ListComboBox and FilterComboBox do not always dispatch `selected-index-changed`

### ISSUE THREAD

**Issue by catwell** [elix/elix#101]
In particular, they do not dispatch it when selecting an item using a mouse (!).

I know why and will send a PR that fixes it shortly.

**Comment by JanMiksovsky** [comment]
Thanks for this report and your PR! Looks good, just wanted to say that it will probably be a few days before I can land this.

**Comment by JanMiksovsky** [comment]
I've merged the PR. This fix will go out in the next release, hopefully in the next week or so.

Thanks again for fixing this, and for taking care to fix it exactly the way we would have.

FYI we're wrapping up some work that affects the Overlay base class, and are seeing some regressions in the appearance of various components that derive from it. (E.g., MenuButton currently does not render correctly.) At the moment, the various ComboBox components have a problem in that the list is not being clipped to the bounds of the popup, so scrolling doesn't work correctly. That's a known problem that we're working on fixing.

BTW if you have a moment, I'd love to hear from you: any thoughts you have on Elix, whether you're using the components for a project, anything you'd like to see in the project. You can send email to jan@component.kitchen.
