### ISSUE TITLE
CrossfadeStage: Unselected items are transparent but can still interfere with interactions inside selected item

### ISSUE THREAD

**Issue by JanMiksovsky** [elix/elix#105]
This issue was first referenced by @bahrus in #104, and I'm opening a new issue to track it.

@bahrus reports:

> I created a [demo](https://bahrus.github.io/elix/tabTest3.html), which, if I'm not mistaken, may indicate something is amiss.
> 
> What you see when open the page appears to be Standard Rooms Detail, which is a details element, inside of which is a button. Expanding the summary ought to show the button inside. It doesn't (for me). But when I switch to the Deluxe button, I see the Deluxe Rooms Detail expanded.

The relevant component here is CrossfadeStage, a subcomponent used inside a Tabs instance in the Serene demo.

CrossfadeStage currently gives the selected item `opacity: 1` and the other, unselected items `opacity: 0`. While that does make the items appear invisible, they're still there on the page, and can prevent the user from clicking through to items — e.g., buttons — on the selected item (here, in the original report, a tab). As one response to this [StackOverflow question](https://stackoverflow.com/questions/4675916/css3-element-with-opacity0-invisible-responds-to-mouse-events) indicates, "You should think of an opacity:0 element as if it was made of glass."

CrossfadeStage can't simply hide the unselected items, as they need to be visible for the animated CSS opacity transition to work. What's needed is for CrossfadeStage to hide all unselected items until the transition effect is needed. It then needs to show the newly-selected item, and leave the previously-selected item visible until the transition effect completes. At that point, it should hide the previously-selected item.

Related feature request from #104: CrossfadeStage should raise an event when the transition effect completes so that the outer page can perform any work of its own once the new selection state has completely finished rendering. Since CrossfadeStage is used as a stage inside of Explorer subclasses like Tabs, Explorer should also be aware of that transition effect complete event, and reraise it. (If it doesn't do that, an effect complete event raised by CrossfadeStage won't bubble up outside of the Explorer's shadow boundary.)

**Comment by JanMiksovsky** [comment]
@bahrus I've checked in a fix for this on the crossfade branch.

1. CrossfadeStage now hides the unselected items with `visibility: hidden`. It waits to hide the previously-selected item until the selection transition effect has completed.
2. CrossfadeStage now raises an event called `selection-effect-finished` after the CSS `transitionend` for the relevant CSS animation has completed. The `detail` of this event includes the `selectedIndex` for the newly-selected item. The order of events is `selected-index-changed` (occurs immediately when the index changes), followed by `selection-effect-finished` (occurs some time later).
3. Explorer (and its subclasses like Tabs) re-raise `selection-effect-finished` if the Explorer's `stage` is a component like CrossfadeStage that raises that event.

If your time allows, please take a look. I've temporarily left some diagnostic console output in /demos/serene.html to verify that UI items on a tab are in fact clickable and that the `selection-effect-finished` event is being raised.

This fix necessitated some changes in TransitionEffectMixin. If you were using that mixin directly, or applying transition effects in Elix-based components of your own, I can go into more details.

**Comment by JanMiksovsky** [comment]
This is now on #master as well.

**Comment by bahrus** [comment]
Thanks for the update.

Has the master branch been deployed to https://component.kitchen/demos/src/serene/*.js yet?

Or is there another url you recommend using?

So far, not seeing any difference.

**Comment by JanMiksovsky** [comment]
No. We generally only update the site with public releases, and only expose a few limited paths to source on our site for things like our tutorial. Beyond that, we're not really set up to support use of Elix source straight off of our server.

It's much better to use a service like https://unpkg.com to get releases in a scalable way or, for production use, to install Elix as a dependency in package.json and use a local copy.

I've published what's on master as a release called 8.0.1-beta.0. You can feed that to unpkg if you want, e.g. https://unpkg.com/elix@8.0.1-beta.0/src/CrossfadeStage.js.

**Comment by JanMiksovsky** [comment]
Since these fixes were released in 8.0.1, I'm closing this out.
