### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by websemantics** [elix/elix#106]
Hi @JanMiksovsky and all contributors

Last night while looking for good Web Components starting point and after seeing Polymer and few others I found Elix and I am impressed!

Just to say thank you for the great array of mixins, the use of es6 modules (that works in the browser), not having a complicated build step, not dependent on an astronomical number of packages, not using elaborate styles and themes, and most importantly the flat folder structure of `src`, ... just beautiful.

**Comment by JanMiksovsky** [comment]
Thanks! We try to do things as plainly and simply as we can, and it's always nice when that approach resonates with other people.

If you'd be willing to share more about the project you're considering Elix for, I'm always interested in hearing that sort of background story through email to jan@component.kitchen.

**Comment by websemantics** [comment]
Nothing specific, migrating older code of various utilities I use for local development. Thanks for the answer and keep up the good work.
