### ISSUE TITLE
Drawer backdrop's maxOpacity hardcoded

### ISSUE THREAD

**Issue by nategreen** [elix/elix#110]
[In the `Drawer`, the backdrop's `maxOpacity` is hard-coded to `0.2`.](https://github.com/elix/elix/blob/17fe77242e6639d22a36c1984cc15c5b2f897b66/src/base/Drawer.js#L199) That makes it impossible to adjust the color to be darker than the default. Overriding it with `::part(backdrop) { opacity: 1 }` effectively disables the `transition`, since the `transition` is overridden while the animation is taking place.

I propose either:
- Changing the default styling to `[part~="backdrop"] { opacity: 1; background: rgba(0, 0, 0, 0.2); }` and setting `maxOpacity` to `1`, or
- Making `opacity` a property of `Backdrop` (or `ModalBackdrop`, or `Drawer`, whichever) that can be used to override the `maxOpacity` here.

**Comment by nategreen** [comment]
I was able to use `::part(backdrop) { transition: opacity 0.25s ease !important; }` as a workaround, but the fading during swipe doesn't work. (Which I'm not excited about, but can live with.)

**Comment by JanMiksovsky** [comment]
Thanks for reporting this.

We've nearly completed a huge effort to factor all aesthetic styling out of the components in src/base. We were almost able to finish that work in the recent 11.0 release. There was one case that proved quite hard to factor properly — the way the base Drawer component has hard-coded opacity measurements. As you noted, there's an unfortunate entanglement of opacity with swiping, and we need more time to fix that.

So sorry that you had to hit that problem yourself! We've got that on the list of issues to address in the next release.

**Comment by JanMiksovsky** [comment]
Your first proposal seems like a good first step — I've checked in a change to Drawer in which it takes the opacity of the backdrop all the way to 1. To compensate, PlainModalBackdrop now defines its background color to have 0.2 opacity per your suggestion.

I like that answer, as it leaves it up to the definer of the backdrop to decide how opaque/transparent they want their backdrop to be.

This leaves the deeper question, however, of whether Drawer should be the business of dealing with backdrop opacity at all. It still feels possible that different design systems may want other transition effects, in which case the linkage of backdrop opacity to swipe state really belongs in PlainDrawer, not Drawer. As noted above, doing that would be quite tricky.

I'm reluctant to add a property to Drawer to govern whether it manipulates opacity, as such properties tend to accumulate over time and make simple components unwieldy.

For now, if this particular change meets your needs, I might leave the opacity handling in Drawer, then revisit later.

**Comment by JanMiksovsky** [comment]
After thinking it over, I decided that adjusting the drawer backdrop's opacity is something that really belongs in a design system component (like PlainDrawer/PlainDrawerWithGrip) and not in the base Drawer component.

The refactoring was a little involved. To help make it easier for a design system like Plain to manipulate opacity (or anything else) during a drawer open/close operation, Drawer now maintains some new state members, including `drawerTransitionDuration`, `openedFraction`, and `showTransition. Using those, the Plain drawer variants can fairly easily calculate what the backdrop opacity should be.
