### ISSUE TITLE
FilterComboBox selects the wrong element when clicked after filter

### ISSUE THREAD

**Issue by c8y3** [elix/elix#119]
The FilterComboBox seems to select the element according to its index in the initial list, rather than in the filtered list.
The issue can be reproduced in the demo : https://component.kitchen/demos/filterComboBox.html.
First type "Cr" in the input.
Then click on the second choice (Cranberry)
=> instead of Cranberry, Akee is now selected in the input (Akee is the second choice from the initial list)

**Comment by JanMiksovsky** [comment]
You are correct, this is a regression.

We're working on a fix.

**Comment by JanMiksovsky** [comment]
This has been fixed on #master, and will go out in the next Elix release.

**Comment by c8y3** [comment]
Thank you for the quick reply and fix.
