### ISSUE TITLE
Drop down appears under other Comboboxes

### ISSUE THREAD

**Issue by kybernetikos** [elix/elix#127]
I'm really enjoying working with elix, it seems to be a high quality set of components, that are shockingly difficult to find elsewhere packaged as well.

When I have an auto complete combo box immediately above another autocomplete combobox the popup appears underneath the lower auto complete combo box.

```html
<!DOCTYPE html>
<html>
<body>
    <script type="module" src="https://unpkg.com/elix@14.0.0/define/AutoCompleteComboBox.js"></script>
    <elix-auto-complete-combo-box aria-label="Pet" value="Cat">
        <div>Cat</div>
        <div>Dog</div>
        <div>Fish</div>
    </elix-auto-complete-combo-box>
    <br />
    <elix-auto-complete-combo-box aria-label="Pet" value="Dog">
        <div>Cat</div>
        <div>Dog</div>
        <div>Fish</div>
    </elix-auto-complete-combo-box>
</body>
</html>
```

Steps:

1. Load the above page in a browser (I've tested in Firefox 80.0b1  and chrome 84.0.4147.105)
2. Click on the top combo box
3. Observe that the 'Dog' combo box is on top of the drop down.

**Comment by kybernetikos** [comment]
![image](https://user-images.githubusercontent.com/430980/89023347-590fb200-d31b-11ea-9320-2197b915711a.png)

**Comment by JanMiksovsky** [comment]
Thanks for submitting this report!

I can reproduce the problem, and will investigate.

**Comment by JanMiksovsky** [comment]
The issue arose because the default styling for the input in a combo box applied a `z-index`. This could cause the input for one combo box to end up above the popup for a second combo box, as in your repro case.

To fix this, I've updated the default styling for Elix combo boxes to avoid use of a `z-index` on the input.

**Comment by kybernetikos** [comment]
Thank you for your quick response!
