### ISSUE TITLE
How to change icon on MenuButton?

### ISSUE THREAD

**Issue by dhubler** [elix/elix#128]
I'm trying to change the icon on the menu button and docs say I should use "up-icon" and "down-icon" CSS part, but nothing is working:

I cannot even change the background color, never mind the image.

                elix-menu-button::part(up-icon) {
                    background: pink;
                }

**Comment by dhubler** [comment]
I decided to try popup button as source instead:

                <elix-popup-button popup-position="above" horizontal-align="right">
                    <i slot="source" class="material-icons menu-btn">settings</i>
                    <elix-menu class="popup">
                        <elix-menu-item>About</elix-menu-item>
                    </elix-menu>
                </elix-popup-button>

and i cannot seem to control the extra padding around the source element.  I'd be happy if i could just control the background-color if i cannot set padding to 0.

![Screenshot from 2020-08-14 14-37-48](https://user-images.githubusercontent.com/8318/90282292-1631fc00-de3c-11ea-8cc3-c617ce1d45e1.png)

**Comment by JanMiksovsky** [comment]
Thanks for spotting this.

It looks like we were using an older format to have an element inside another one export its parts. It looks like early versions of the `exportparts` attribute accepted a space-delimited list of parts, but the standard now requires a comma-separated list.

I'll updated MenuButton to use a comma-separated list.

**Comment by JanMiksovsky** [comment]
This fix should be included in the forthcoming public release, out in the next couple of weeks.
