### ISSUE TITLE
regarding TypeScript; change documentation || example project

### ISSUE THREAD

**Issue by imme-emosol** [elix/elix#129]
The documentation currently contains the following text:

> TypeScript
> 
> See the sample TypeScript project showing how to use Elix components in a TypeScript application. Elix includes TypeScript declaration files so that you can confirm that interactions with Elix components are type safe.

But the example shows one component and not even in what I would consider an application.

**Comment by JanMiksovsky** [comment]
First of all: thanks for filing an issue.
Second: many apologies for the slow response. I'd meant to come back to this, but didn't. Sorry about that.

I understand your expectation that the sample application isn't as elaborate as you were expecting. We've occasionally considered developing a more full-featured sample, but we've been busy simply keeping the basic components working to meet people's expectations.

For the time being, I will say that I believe most TypeScript users are simply looking for a demonstration of how to incorporate an Elix component into their own project. Whether the sample shows one component or many makes no difference to that type of visitor — they just need to see how to do it. And even if this "application" is trivial, I still think it's meaningful to describe it that way.
