### ISSUE TITLE
Switcher component feature request

### ISSUE THREAD

**Issue by nouman91** [elix/elix#134]
I would like to request a new component **Switcher** also known as a toggle.  For reference:

[Switcher](https://material-ui.com/components/switches/)

**Comment by JanMiksovsky** [comment]
Thanks for the suggestion.

We've updated the [list of desired components](https://component.kitchen/elix/vision) to include your suggestion of a toggle switch (currently #128 on the alphabetical list). That seems distinct enough from a toggle button, which might reflect its state by showing itself in a persistent pressed/highlighted state, say. Among other things, it would be good for a toggle switch to support a touch swipe gesture to change state.
