### ISSUE TITLE
How to get the value property (and not the text inside the div) for AutoCompleteComboBox

### ISSUE THREAD

**Issue by jfhenon** [elix/elix#143]
Begin with a clear and concise description of the bug.

**Steps that reproduce the issue**

Please see codepen below 
https://codepen.io/jfhenon/pen/RwRvzyq

If I select a line with the above component, 

When I select an element of the list, I expect to get the "value" property (i.e."cat") but my code only give me the text inside the div  ("chat"). 

What did I do wrong?

**Comment by jfhenon** [comment]
I can actually get the expected value with e.target.selectedItem.getAttribute('value'). 
I guess my question is now: is this the right way to do this

**Comment by JanMiksovsky** [comment]
You should be able to use the combo box's [selectedItemValue](https://component.kitchen/elix/AutoCompleteComboBox#selectedItemValue) property. This will return the `value` attribute of the selected item.
