### ISSUE TITLE
can't "get started"; cloning plain-example gives permission denied

### ISSUE THREAD

**Issue by jmagaram** [elix/elix#145]
I tried following the instructions on [this page](https://component.kitchen/elix/getting_started). When I type ``git clone git@github.com:elix/plain-example.git`` I get the error below. I'm not an expert on Git but have used it successfully before. In the same command prompt I typed ``git clone https://github.com/material-components/material-components-web.git`` and it worked fine.

    git
    Cloning into 'plain-example'...
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.

**Comment by jmagaram** [comment]
No problem typing this...

``git clone https://github.com/elix/plain-example.git``

**Comment by jmagaram** [comment]
Ok I've read about SSH and got it working using your specific instructions. I'll leave it to you to close this if you think no action should be taken. I suspect there are plenty of git users who have not set up the SSH keys.

**Comment by JanMiksovsky** [comment]
Hi @jmagaram! Thanks for taking a look at Elix, and sorry for the slow response. (After years of working on this, you've caught me in a period where I'm heads-down on other things.)

Your recommendation makes sense, and we've updated that page (and the related one at https://github.com/elix/plain-example) to use the `https://` form instead.
