### ISSUE TITLE
openedchange isn't reliably raised for Popup

### ISSUE THREAD

**Issue by jmagaram** [elix/elix#146]
I'm trying to use Elix in a Blazor project. I wrapped the Popup element in a Blazor component and tried to listen for the ``openedchange`` event. I coded my tests so each time the event was raised I'd display something like "popup is open : true" or "popup is open : false" to the web page. It seemed to work very reliably when I opened the popup via a button or dismissed the popup by clicking outside its bounds. So my plumbing seemed to be ok. Then I added a button INSIDE the popup that called close to dismiss it. The popup became hidden - my close button worked - BUT the openedchange event was not firing. I tried a few different ways to manually close the popup, like setting the "opened" property to false; this again caused the popup to close but again no event was raised. I thought maybe the event was getting raised but the message not being displayed, but could not get any proof of this through debugger messages, Console.Log, or other means. So it seemed like the event was not being raised.

I figured maybe this was a weird problem with Blazor so I tried to build a plain vanilla javascript project to repro. I used the Chrome dev tools to watch what is happening. This is tough to work with because it seems every time I attempt to Console.Log what is happening the Popup gets stuck in the open state on the screen, or won't open at all. The dev tools are interfering with the behavior of the app. But in any case through my experimentation it seems like the ``open`` and ``close`` events will work. But the ``openedchange`` event doesn't.

I'm really new to javascript and Chrome debugging so it is possible I'm doing something wrong here. But because I can't get reliable behavior in Blazor OR vanilla javascript, I think there might be a problem with the ``openedchange`` event.

For repro, see github referenced in later comment.

-- deleted old code here --

**Comment by jmagaram** [comment]
I cleaned up my sample web page to get a better sense for what is happening. And the behavior is really weird. When I run this, each time I click "open popup" I see the count for how many times the popup is opened increasing, but the popup doesn't appear at all. And the close count never gets beyond 0. If I use the "addEventListener" method no events seem to get raised. I'm really frustrateed. With Blazor I got it almost working - the only time openedchange did not fire was when  I put a button inside the popup to dismiss it. And now, with vanilla javascript, almost nothing seems to work. The behavior is very erratic. I'm going to publish my repro scenario on github. I must really be missing something basic here.

    <!DOCTYPE html>
    <html lang="en">

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <title>Simple application using an Elix component</title>
      <script type="module">
        import Popup from './node_modules/elix/define/Popup.js';
      </script>
      <script type="text/javascript">

        var openCount = 0;
        var closeCount = 0;
        var openedchangeCount = 0;

        function displayMessage(s) {
          var p = document.getElementById("status")
          p.innerText = s
        }

        function displayCounts() {
          var i = document.getElementById("openCount")
          i.innerText = openCount
          var j = document.getElementById("closeCount")
          j.innerText = closeCount
          var k = document.getElementById("openchangedCount")
          k.innerText = openedchangeCount
        }

        function attachEventHandler() {
          var p = document.getElementById("samplePopup")

          // OPEN event

          // p.addEventListener("open", (e) => {
          //   openCount++;
          //   displayCounts();          
          // });

          p.open = (e) => {
            openCount++;
            displayCounts();
          };

          // CLOSE event

          // p.addEventListener("close", (e) => {
          //   closeCount++;
          //   displayCounts();
          // });

          p.close = (e) => {
            closeCount++;
            displayCounts();
          };

          // OPENEDCHANGE event

          // p.addEventListener("openedchange", (e) => {
          //   openedchangeCount++;
          //   displayCounts();
          // });

          p.openedchange = (e) => {
            openedchangeCount++;
            displayCounts();
          };

          displayMessage("finished attaching event handlers")
          displayCounts();
        }

      </script>

      <style>
        body {
          font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
          font-size: 15px;
        }
      </style>
    </head>

    <body>
      <div>
        Status: <span id="status"></span>
      </div>
      <div>
        Open count: <span id="openCount"></span>
      </div>
      <div>
        Close count: <span id="closeCount"></span>
      </div>
      <div>
        OpenChanged count: <span id="openchangedCount"></span>
      </div>
      <div class="demo padded">
        <button onclick="attachEventHandler()">Attach event handlers</button>
        <button id="showPopup" onclick="samplePopup.open()">Open popup</button>
        <elix-popup id="samplePopup">
          <div style="padding: 1em;">
            Here's a popup.
            <button onclick="samplePopup.close()">close it!</button>
          </div>
        </elix-popup>
      </div>
    </body>

    </html>

**Comment by jmagaram** [comment]
Here is the project:

https://github.com/jmagaram/ElixExperiments

**Comment by jmagaram** [comment]
Just realized that the code I've been debugging is not my current code. There is some kind of cache when doing npx http-server. This explains the weird inconsistent behavior. Need to figure out how to delete the cache and see what is really happening.

**Comment by jmagaram** [comment]
I'm missing something really fundamental and getting extremely frustrated. I edited the typescript example project to add this code, and yet I can't seem to get the event to ever fire. When I look in the Chrome dev tools I see the event listener is attached, it just never hits a breakpoint inside the event handler.

    <body>
      <p>
        This page shows how Elix components can be used in the context of
        a TypeScript application. This page shows two instances of the Elix
        DateComboBox component. The first is created via markup; the second
        is created at runtime in TypeScript. Both work the same way.
      </p>
      <elix-date-combo-box id="dc" date="1 Jan 2020"></elix-date-combo-box>
    </body>


    <script>
      dc.addEventListener("datechange", () => {
      });
    </script>

**Comment by jmagaram** [comment]
For completeness here is the Blazor code that wraps the Elix Popup. This works. From C# I can open and close the popup. I can also listen for when the popup state changes from opened to close. The problem is that if I close the popup using a button inside the popup (calling the Close() method), the popup closes - good - but the openedchange event never fires - bad.

First, the javascript interop code...

    var ElixPopup = ElixPopup || {};

    ElixPopup.addOpenedChangeEventListener = function (element, assemblyName, method, helper) {
        element.addEventListener("openedchange", (event) => {
            const isOpened = event.currentTarget.opened;
            helper.invokeMethodAsync(assemblyName, method, isOpened);
        })
    };

    var HtmlElement = HtmlElement || {};

    HtmlElement.setProperty = function (element, k, v) {
        element[k] = v;
    }

And here is the Blazor C# code...

    @inject IJSRuntime JSRuntime
    @implements IDisposable
    @using Common

    <elix-popup @ref="_popup">@ChildContent</elix-popup>

    @code {
        ElementReference _popup;
        DotNetObjectReference<CallbackHelper<bool>> _openedChangeCallbackReference;

        protected override async Task OnAfterRenderAsync(bool firstRender) {
            if (firstRender) {
                var _openedChangeCallback = new CallbackHelper<bool>(isOpened => OpenedChange.InvokeAsync(isOpened));
                _openedChangeCallbackReference = DotNetObjectReference.Create(_openedChangeCallback);
                await JSRuntime.InvokeVoidAsync("ElixPopup.addOpenedChangeEventListener", _popup, "WebApp", "Invoke", _openedChangeCallbackReference);
            }
        }

        public async ValueTask Open() => await JSRuntime.InvokeVoidAsync("HtmlElement.setProperty", _popup, "opened", true);

        public async ValueTask Close() => await JSRuntime.InvokeVoidAsync("HtmlElement.setProperty", _popup, "opened", false);

        [Parameter]
        public RenderFragment ChildContent { get; set; }

        // OependChange event is NOT firing when this is closed from clicking a button within the content
        // But the event is fired if click outside. Weird.
        [Parameter]
        public EventCallback<bool> OpenedChange { get; set; }

        public void Dispose() => _openedChangeCallbackReference?.Dispose();
    }

**Comment by jmagaram** [comment]
I tried working with the Elix Drawer. Same or similar problem as with the Popup, probably since both use the same mixin. From within Blazor, I can't get notified when the Drawer is opened. And I only get notified when the Drawer is closed by clicking outside of it, on the overlay. If I click a button inside the Drawer that closes it, the close event handler is not called, just like the Popup. I thought maybe there was an issue with calling open or close from Blazor which triggers the javascript event handler, but then Blazor is too busy/blocked to hear the event. I'm using async for all my calls so I don't think that is the issue. But to test it I closed and opened the Drawer using a 3 second settimeout. I figured this fire-and-forget method would free up Blazor to hear the response. No change. When I set breakpoints inside the javascript below using the browser dev tools I see the same behavior - the open event handler is never called.

I wish I could try to repro this in a vanilla javascript environment - no Blazor - but can't get any events to fire for some reason (see my previous comments on this issue).

        ElixOpenCloseMixin.addOpenedChangeEventListener = function (element, assemblyName, method, helper) {
            if (element == null) return;
            // Weird behavior for this event handler. It never seems to break for an
            // open event. It is called for a close event when closed by clicking
            // outside the component (Popup, Drawer), but is not called if the component
            // is closed manually by clicking a button inside the component.
            element.addEventListener("openedchange", (event) => {
                const isOpened = event.currentTarget.opened;
                helper.invokeMethodAsync(assemblyName, method, isOpened);
            })
            // This event handler never seems to get invoked.
            element.addEventListener("open", (event) => {
                helper.invokeMethodAsync(assemblyName, method, true);
            })
            // This event handler is only called when I click outside the component, but
            // not when I manually close the component by clicking a button inside the
            // component.
            element.addEventListener("close", (event) => {
                helper.invokeMethodAsync(assemblyName, method, false);
            })
        };

**Comment by JanMiksovsky** [comment]
@jmagaram Apologies for the slow response — the last month has been one thing after another.

This appears to be an effect of the event pattern in Elix, which in turn is driven by the [fundamentally confusing nature of property change events in HTML](https://github.com/webcomponents/gold-standard/wiki/Property-Change-Events). The basic web pattern is: property change events like `openedchange` only fire in response properties which change as a result of user activity (clicks, etc.) handled internally by the component. If the page hosting a component changes a component's property from the outside, the page itself is assumed to already know about the change in property, and is therefore responsible for responding accordingly.

Example: a native `<input type="checkbox">` element fires a `change` event if the user clicks the check box themselves — but if the page sets the input's `value` property, the `change` event does *not* fire.

See also this related [Elix issue in the same general area](https://github.com/elix/elix/issues/100).

In your example, you have

```html
    <elix-popup id="samplePopup">
      <div style="padding: 1em;">
        Here's a popup.
        <button onclick="samplePopup.close()">close it!</button>
      </div>
    </elix-popup>
```

The button with the onclick looks like it's raising the event from inside the popup. But from the viewpoint of the DOM, that button is sitting on the page. It's the page that's ultimately calling the popup's `close()` method. The `elix-popup` therefore does *not* raise the `openedchange` event.

I find this standard behavior confusing, to say the least, but Elix components do their best to emulate the nature of the underlying web platform, and that's how the web platform generally works.

Instead of having the button call `samplePopup.close()`, you can have the button call some method on the page that closes the popup, and then calls some `handlePopupClose()` routine to do whatever you want to have happen after the popup closes. At the same time, listen to the popup's `openedchange` events so you can respond the popup changing as a resulting in UI behavior handled by the popup (like clicking outside the popup). The event listener for that event can call the same shared `handlePopupClose()` routine.

Another route would be to create your own subclass of the Elix Popup class that included the "close it!" button. This button would be sitting inside the popup component, and would be able to tell the popup to raise the `openedchange` event. Let me know if you want to pursue that route and I can provide some guidance.

**Comment by jmagaram** [comment]
Thanks Jan. I am interpreting this as "if my code makes the change I won't get notified by an event." I did attempt to hook up an event handler to the date navigator - see earlier in this issue - and couldn't get it to fire. Seems like in that situation it should fire.

**Comment by JanMiksovsky** [comment]
I'm trying to reproduce the problem you describe, and the DateComboBox component is raising datechange as I expect.

https://codepen.io/JanMiksovsky/pen/abmKPNa?editors=1011

It's possible I'm misunderstanding your expectations. Can you elaborate?

**Comment by jmagaram** [comment]
Can't reproduce the DateComboBox problem. I think the problem was difficulty using http-server. It was caching old code.
