### ISSUE TITLE
How do I style just the selected tab when using elix-tabs

### ISSUE THREAD

**Issue by dhubler** [elix/elix#147]
I can use this to style tabs
```
elix-tabs::part(proxy) {
  font-weight: bold;
}
```
but i don't think there's a way to style *just* the selected tab.  

This doesn't work in any browser
```
elix-tabs::part(proxy)[selected] {
  color: red;
}
```

**Comment by JanMiksovsky** [comment]
The bad news: the feature you want is requires the ability to style a part depending upon some aspect of its current state (e.g., selected or not). That feature is not yet supported in production browsers.

The good news: there is a standard CSS selector called [:state()](https://developer.mozilla.org/en-US/docs/Web/CSS/:state) which is coming.

The only browser that implements `:state()` at this point is Google Chrome Canary. We participate in the standards efforts to do what we can to hasten the advent of `:state()` in other browsers, but beyond that, there's not much we can do.

Most Elix components are already prepared for `:state()`. You can do the following with Elix and Chrome Canary today:

```css
elix-tabs::part(proxy):state(selected) {
  color: red;
}
```

The best way to do what you want in production browsers today is to explicitly create your own tab button children inside elix-tabs. You can assign such buttons to the "proxy" slot, and they'll end up being used as the tabs. See https://github.com/elix/elix/blob/master/demos/tabsWithTabButtons.html for an example.

That approach puts the tabs in the light DOM, where you can style them with the `[selected]` CSS selector.

**Comment by JanMiksovsky** [comment]
Assuming that the response below answered the original question — ever if it's not the answer you were looking for — I'm going to close this. If your question wasn't answered, though, feel free to reopen.
