### ISSUE TITLE
How can i change style of AlertDialog ?

### ISSUE THREAD

**Issue by AgriyaDev5** [elix/elix#158]
1. How can i change AlertDialog choices buttom style change? 
2. How can i change AlertDialog  text font and style change ?

OR 

how can i overwrite the AlertDialog templete ?

**Comment by JanMiksovsky** [comment]
Styling components is still unfortunately a complex task. The page on [customizing](https://component.kitchen/elix/customizing) lays out the basic options.

Assuming you want your customizations to work on Safari and/or Firefox, then you can use a combination of the following:

* [Replaceble element parts](https://component.kitchen/elix/customizing#replaceable-element-parts) for the choice buttons. You can define whatever kind of button you want as a component class, then use that as the dialog's `choiceButtonPartType`.
* [Template patching](https://component.kitchen/elix/customizing#template-patching). You can subclass AlertDialog, then override the `template` and add whatever styles you want.

You can see both of these techniques in action in the [source for the PlainAlertDialog component](https://github.com/elix/elix/blob/main/src/plain/PlainAlertDialog.js), which is what you get when you instantiate `elix-alert-dialog`.

Let me know if you need any help with that.

**Comment by JanMiksovsky** [comment]
Since there doesn't seem to be more to address here, I'm going to close this. Please reopen if necessary.
