### ISSUE TITLE
Button: Not announcing that its a button with a screen reader

### ISSUE THREAD

**Issue by tmcconechy** [elix/elix#179]
Was looking for a solution to an issue im having on my buttons and come to find yours do a similar thing and have similar logic. So just posting for your info / to see if we can think of a solution...

Basically it means the buttons in elix are not identifying as buttons. (in a web component context)

**Steps that reproduce the issue**
1. Go to https://component.kitchen/elix/TooltipButton
2. Turn on the chrome vox plugin in chrome settings (after installing)
2. Tab to the buttons with the tooltips on them
3. Listen that it says "One One"

**Expected behavior**
It should say "One button One". If you take this example:

```
<button aria-describedby="test">One</button>
<span id="test">One</span>
```

It behaves correctly and says "One Button One".

**Comment by JanMiksovsky** [comment]
Hmm, screen reader compatible area is a tricky area. We generally test with Apple VoiceOver on macOS and Microsoft Narrator on Microsoft Windows.

I just did a quick test of the above demo in VoiceOver on Chrome and Safari, and in both cases Voice announces the TooltipButton as a button. Given that, I think the component is working as expected, or at least at the limits of what we have the bandwidth to test and support. Sadly, we don't have enough bandwidth ourselves to tackle other products — there are just too many of them, and they tend to exhibit distinctive quirks.

Web component accessibility is at the bleeding edge of what's possible today, so it's possible that the plugin you mention has an issue. If you can pin that down, you might be able to file a bug with the plugin vendor.

Alternatively, it's possible that something is theoretically possible according to the HTML spec, but in practice we've done something that only works in VoiceOver and Narrator. In that case, if you want to investigate further and propose a change (or, better yet, submit a PR), please let us know.

**Comment by tmcconechy** [comment]
OK thanks for the feedback. Your right in that voice over works as expected. I guess just chrome vox is a bit behind.
I did find that doing

```
<elix-tooltip-button role="button>
```

Sort of worked but read things in the wrong order. But i understand the bandwidth issue so will close this for now. Just wanted to see if you had any feedback.. Might do a PR later if needed.

Thanks!
