### ISSUE TITLE
Events(Tap,mousedown) Not triggered after moving from 7 to 12.

### ISSUE THREAD

**Issue by dinesh5k** [elix/elix#183]
Hi There,

I have moved my code from Elix 7 to 12 and Tap event is not getting triggered on FilterListBox, I went thru lot of documentation and no solution yet. Could you please point me what I am doing wrong.

**Comment by dineshmamidi5** [comment]
Thank you for the reply.

I checked out your demo, my code is like this, the tap event is not triggered and I had to add my own code to trigger the tap.
Please let me know if you may have any suggestions.

class ExtendedFilterListBox extends FilterListBox {
  get [internal.defaultState]() {
    return Object.assign(super[internal.defaultState], {
      generic: false
    });
  }
 
  //this is not triggered
  [internal.tap](/** @type {MouseEvent} */ event) {
    if (super[internal.tap]) {
      super[internal.tap](event);
    }
    this._fireValueChanged();
  }
   
  [internal.render](/** @type {PlainObject} */ changed) {
    if (super[internal.render]) {
      super[internal.render](changed);
    }
    if (changed.items) {
      this._updateOddRows();
    }
    //this work around is picked up
    this.addEventListener('click', (e) => {
      this._fireValueChanged();
    });

  }
  get [internal.template]() {
      const style = this.styles();
      const result = super[internal.template];
      result.content.append(
        html`
        <style>
          ${style}
        </style>
         `
      );
    return result;
  }
 
}

**Comment by dinesh5k** [comment]
I figured out the issue, the internal import is missing Events, so I changed the import from core to base and things started working again.

**Comment by JanMiksovsky** [comment]
Many thanks for the follow-up.
