### ISSUE TITLE
How manually update input value get from NumberSpinBox ?

### ISSUE THREAD

**Issue by AgriyaDev5** [elix/elix#199]
URL: https://component.kitchen/elix/NumberSpinBox

How manually update input value get from NumberSpinBox ?

Example: https://codepen.io/agriyadev5/pen/poPXerX

change event not trigger.

**Comment by JanMiksovsky** [comment]
Sorry for the slow response. The Elix maintainers are on hiatus this summer, and should be back at work in mid-September. I’ll look into this problem then, but realize that that’s probably not fast enough for your needs. Thanks for your understanding.

**Comment by JanMiksovsky** [comment]
It looks like this was an oversight in the original SpinBox base class implementation — the class didn't define a change event at all.

This should be fixed on the main branch, and the fix will go out in the next minor Elix release. The change event should fire when the user modifies the spin box's value through the buttons or by typing.

If you have time, give what's on main a try and let me know if it addresses your issue.

**Comment by JanMiksovsky** [comment]
This has now been released as Elix 15.0.1.
