### ISSUE TITLE
FormElementMixin issue with Firefox 93

### ISSUE THREAD

**Issue by dinesh5k** [elix/elix#208]
Hi There,

I have a panel with 2 input boxes which are not inside a form element.

in Firefox 93 the page throws an error saying (this[internal.nativeInternals].setValidity is not a function.

after a bit of research, we learned firefox enabled ElementInternals.shadowRoot and HTMLElement.attachInternals, this is causing render function in FormElementMixin to get into [internal.nativeInternals], which is still undefined for other browsers.

could you please suggest what we should do to fix this.

Thank you.

**Comment by JanMiksovsky** [comment]
This has now been released in Elix 15.0.1.
