### ISSUE TITLE
Input component does not allow "type" attribute

### ISSUE THREAD

**Issue by alexfict** [elix/elix#233]
It is not possible to set the `type` attribute on an elix input component.

**Steps that reproduce the issue**
1. Create a page with `<elix-input type="email">`.
2. Throws error: Uncaught TypeError: setting getter-only property "type". (in AttributeMarshallingMixin.js)

**Expected behavior**
Delegate `type` attribute to the inner input element, as it is done with `name` attribute.

**Comment by JanMiksovsky** [comment]
Thanks for filing this issue!

I've pushed a fix to main, and it will go out in the next Elix release. In the meantime, if your time allows you can verify if that fixes the issue for you.

**Comment by alexfict** [comment]
Looks promising. Thanks for the quick response!
