### ISSUE TITLE
Carousel content can overflow (min-width: auto for flex)

### ISSUE THREAD

**Issue by geonanorch** [elix/elix#238]
The slides shown in a carousel can actually be wider than the container, causing some of the content to be truncated.

**Steps that reproduce the issue**
See [this pen](https://codepen.io/geonanorch/pen/vYpaaVE), which shows the issue in Vivaldi (Chrome-based) and Firefox:
* for confirmation the slots can be inspected, their width is 369px instead of 250px
* in fact the width is wrong up to the `#arrowDirectionContainer` element 

**Expected behavior**
Unless the content is not breakable (very long word, image with large set width, etc...) I expect it to wrap within the slide, whose width should be 100% of the containing carousel.

**Further comments**
* After pulling my hair for a long while, I found out that the issue comes from that special rule for flex children, where by default we have `min-width: auto` ([spec here](https://www.w3.org/TR/css-flexbox-1/#min-size-auto), this [stackoverflow entry](https://stackoverflow.com/questions/36247140/why-dont-flex-items-shrink-past-content-size) is pretty popular, too).
* Based on how the carousel is implemented (`slidingStageContent`), the carousel's stage ends up with a `min-width` equal to **_the sum of_** the computed values of individual slides' `min-width` (369px is double the size of the `<span>` element in the `<h1>` header in the pen above), so the more slides we have the worse the overflow gets.
* one simple fix it to set `min-width: 0` on the `#arrowDirectionContainer` element (as per issue #161 I would rather not use `overflow: hidden`). Unfortunately the fix is not applicable from outside the component.

**Comment by JanMiksovsky** [comment]
Apologies for the slow response — since it's no longer my primary focus, I can only work on Elix in my spare time these days. With that in mind, it's extremely helpful to receive such detailed bug reports, all the more so when you can identify a specific fix that should work. Thanks for that.

I've applied your proposed `min-width: 0` fix and it seems to work for me. If your time allows, please verify that what's on #master works for you as well.

**Comment by geonanorch** [comment]
No worries, I can certainly understand that. The time-to-reward ratio is a general flaw of the current open source model...
My thanks to you for applying the fix, I am glad that I could contribute something. No time right now to test, but I had a look at the commit and it corresponds with what I had been using.
