### ISSUE TITLE
Typescript "noImplicitAny" fails on method attributeChangedCallback in shared.d.ts

### ISSUE THREAD

**Issue by alexfict** [elix/elix#247]
A potentially really quick fix. When running typescript compiler I get the following errors
`Parameter 'attributeName' implicitly has an 'any' type`
`Parameter 'oldValue' implicitly has an 'any' type`
`Parameter 'newValue' implicitly has an 'any' type`

Proposal: add type `any`, (or even a more specific type?) to method signature in `elix/src/core/shared.d.ts`

`attributeChangedCallback?(attributeName:any, oldValue:any, newValue:any): void;`

**Comment by JanMiksovsky** [comment]
I'm sorry I didn't notice this bug before — I just got the notification that you'd closed it, but I don't think I saw the initial bug report. Sorry about that.

If this is still interesting to you, please let me know.
