### ISSUE TITLE
Carousel not compiling to library

### ISSUE THREAD

**Issue by nlighteneddesign** [elix/elix#248]
Begin with a clear and concise description of the bug.

**Steps that reproduce the issue**
I am importing the elix carousel component into a native web component: import CarouselWithThumbnails from ### 'elix/define/CarouselWithThumbnails.js';
When in storybook the carousel works as expected.
When compiling a production artifact I receive hundreds of errors regarding babel runtime. I am using babel runtime. Do you have a recommended babel config for compiling this project?

Here is the compile error 
```
WARNING in ./node_modules/elix/src/base/TouchSwipeMixin.js 210:23-42
    "export 'default' (imported as '_regeneratorRuntime') was not found in '@babel/runtime-corejs3/regenerator'
     @ ./node_modules/elix/src/base/Carousel.js
     @ ./node_modules/elix/src/base/CarouselWithThumbnails.js
     @ ./node_modules/elix/src/plain/PlainCarouselWithThumbnails.js
     @ ./node_modules/elix/define/CarouselWithThumbnails.js
```

Here is the babel config:
```
use: {
            loader: 'babel-loader',
            options: {
              presets: ['@babel/preset-env'],
              plugins: [
                [
                  '@babel/plugin-transform-runtime',
                  {
                    'regenerator': true,
                    'corejs': 3
                  }
                ],
                ['@babel/plugin-proposal-private-property-in-object', { 'loose': true }],
              ]
            }
          }
```
I have those plugins and core js required in package.json
**Expected behavior**
Babel will compile the js into a file I can load in and utilize the carousel.

**Comment by nlighteneddesign** [comment]
I ended up getting it with this babel config:
```
options: {
              'exclude': 'node_modules/**',
              presets: [
                ['@babel/preset-env', {
                  'useBuiltIns': false
                }]
              ],
              plugins: [
                [
                  '@babel/plugin-transform-runtime',
                  {
                    'regenerator': true,
                    'corejs': 3
                  }
                ],
                ['@babel/plugin-proposal-private-property-in-object', { 'loose': true }],
                ['@babel/plugin-proposal-private-methods', { 'loose': true }],
                ['@babel/plugin-proposal-class-properties', { 'loose': true }],
              ]
            }
```
I'll leave this up in case there is another recommendation"

**Comment by JanMiksovsky** [comment]
Sorry for not following up on this — for various reasons, I haven't had any time to invest in Elix lately. Thanks for posting your solution!

It's been a very long time since I used Babel. The Elix code base is as vanilla as I can make it, so I'm surprised Babel has trouble with it. If there's some specific (hopefully simple) thing you think Elix should be doing differently, please let me know.

**Comment by nlighteneddesign** [comment]
I actually switched to glide because ELIX carousel had some difficult to resolve accessibility issues around the buttons. If I recall correctly the buttons didn't have the correct aria attributes.

**Comment by JanMiksovsky** [comment]
Okay, thanks for the update
