### ISSUE TITLE
MenuItem and DropdownList, checkmark icon should be optional

### ISSUE THREAD

**Issue by imagoiq** [elix/elix#268]
Hi,

I'm new to Elix and tried to customize a DropdownList. I'm not sure if I'm right, but by default, I use an OptionComponent for item, there is an SVG icon called "checkmark". I've tried to remove it, but It cannot find a way.

I can understand that it can be useful on the accessibility side, but even though, I'm uncertain if it should be part of it by default. Or perhaps it should be at least defined as a part? Am I missing something, is there already a way to avoid it?

**Comment by JanMiksovsky** [comment]
The checkmark is part of the Plain visual style that's provided by default.

If you want a list option without a checkmark, you can use the one defined in `src/base/Option.js`. That component isn't registered by default, so you'll need to call `customElements.define` yourself.

See https://codepen.io/JanMiksovsky/pen/ExpvBYy

**Comment by imagoiq** [comment]
Thanks for the example, it's already much clearer in my head, I didn't understand until now what was this "Plain reference design system".
