### ISSUE TITLE
Hyphen delimited attributes get not tracked by the reactivity system

### ISSUE THREAD

**Issue by alexfict** [elix/elix#273]
When using custom attributes with a hyphen, e.g. "button-text" the attribute's value is not reflected by the corresponding property buttonText as it is described in the AttributeMarshallingMixin.

A minimal working example to reproduce the behavior:

```ts
export default class JnFoo extends ReactiveElement {
  get [defaultState]() {
    return Object.assign(super[defaultState], {
      buttonText: "initial state",
    });
  }

  get buttonText(): string {
    return this[state].buttonText;
  }

  set buttonText(buttonText: string) {
    this[setState]({ buttonText });
  }

  get [template]() {
    const result = templateFrom.html`<pre>Foo components's button text: ${this[state].buttonText}`;
    return result;
  }
```

When using this component like `<jn-foo button-text="updated state"></jn-foo>` I expect it to display "updated state" but it still show "inital state".

Things work fine when changing the attribute name to "buttontext" **or** overwriting `attributeChangedCallback` with the default implementation found in AttributeMarshallingMixin (just copy pasted).

**Comment by JanMiksovsky** [comment]
Many thanks for providing such a clear repro case.

The ShadowTemplateMixin provides the initial rendering of the template, but does not automatically update the component DOM after that. As it turns out, when you set an attribute like `button-text="updated state"`, that change will be applied *after* the template has been rendered. So your sample code is always rendering the initial state.

Elix expects you to explicitly tell it what you want to update in the DOM when the state changes; see [Rendering](https://component.kitchen/elix/ReactiveMixin#rendering). To have changes in the `buttonText` state appear in the DOM, you'll need to make two changes:

1. Wrap the part of the template you want to update in an element with an ID.
2. Implement the `[render]` method so that, if the `buttonText` state has changed, you update the text of the element with the ID.

```js
    [render](changed) {
      super[render](changed);
      if (changed.buttonText) {
        this[ids].text.textContent = this[state].buttonText;
      }
    }

    get [template]() {
      const result = templateFrom.html`
        <pre>
          Foo components's button text: <span id="text"></span>
        </pre>`;
      return result;
    }
```

Does that make sense?

**Comment by alexfict** [comment]
Hi and thanks for the quick response! Your code snippet does make totally sense and I actually implemented it like this in my code. However, I didn't add it to the repro example since it applies the first DOM change correctly when I simply rename the attribute to sth. like "buttontext" (removing the hyphen). Or as mentioned earlier overwriting `attributeChangedCallback`.

That's why I am wondering if it could be an hyphen related issue.

Especially the 2nd workaround prompts questions. Does some other Mixin eventually override AttributeMarshallingMixin's `attributeChangedCallback`?

**Comment by JanMiksovsky** [comment]
I'm not quite seeing what you're seeing.

First: it looks like I got the order of operations incorrect above. AttributeMarshallingMixin appears to invoke property setters for attributes set in HTML before ShadowTemplateMixin creates the template. If the property setter sets state, then the template will include that state in the template. Sorry for the confusion.

That said, I don't see what you mean about removing the hyphen from the attribute. AttributeMarshallingMixin converts attributes to camelCase property names, so a `button-text` attribute becomes a `buttonText` property, but a `buttontext` attribute maps to a `buttontext` property (with the first "t" lowercase). I don't see how the property can get set in that case — the component has a `buttonText` property, not a `buttontext` property.

To make sure we're on the same page, I created a live repro at https://codepen.io/JanMiksovsky/pen/eYwYgeN?editors=1010

This renders "updated state" as you say — but if I change the attribute name to "buttontext" without a hyphen, it renders "initial state". This is the behavior I'd expect. I see that behavior in current Chrome, Firefox, and Safari.

Do you see something different?

**Comment by alexfict** [comment]
It turned out to be a dependency issue in my project, some kind of npm cache I am not aware of causes the error. Anyway, deleting `node_modules` and reinstalling deps solved the problem.

I am sorry for wasting your time. Many thanks for your support anyhow!
