### ISSUE TITLE
Build doesn't work on Windows

### ISSUE THREAD

**Issue by JanMiksovsky** [elix/elix#34]
From @svastanesto:

> I had some problems with running the build, which turns out to be due to the fact that I am on windows. So slash is different, in the split() and lastIndexOf() part of the script in tasks/wphelper.js (key.lastIndexOf('\\') + 1)).key.split('\\').pop(); Of course it needs to be fixed so its platform independent. And I also needed to add {shell: true} in lintHelper.js  (let task = spawn( 'jshint', args, {stdio: 'inherit', shell: true});) https://github.com/nodejs/node-v0.x-archive/issues/2318#issuecomment-263852511 
> 
> So I got it to build now at the end without errors. However, it looks like babel is not transpiling, and I am left with classes in demos.js, which then breaks in IE 11 of course. 
> But maybe it would not work anyway, due to those breaking changes that you mentioned in web components polyfill?

**Comment by robbear** [comment]
I'll be looking into Windows build issues very soon. Thanks for the report, @svastanesto.
