### ISSUE TITLE
Can't see Elix component in context of Angular dynamic component sample app

### ISSUE THREAD

**Issue by JanMiksovsky** [elix/elix#78]
From Twitter user @SwConsults:

> I have a quick question.  I"m able to consume Elix within an Angular App, but when I place Elix or any Web Component within a Dynamically Generated Component, there's no errors but the component does not show either.  Have you seen this issue before?
>
> im using this sample code: https://stackblitz.com/angular/mrxxaqgmrel … ( which is the official code from Angular https://angular.io/generated/zips/dynamic-component-loader/dynamic-component-loader.zip … ).  By adding 2 lines of code into the hero-profile.component.ts there's no errors but the component never renders.  I also imported import { CUSTOM_ELEMENTS_SCHEMA }    from '@angular/core'; and schemas: [CUSTOM_ELEMENTS_SCHEMA].  Any ideas?

Filing this as an issue so we can track and hopefully help out other Angular users.

**Comment by JanMiksovsky** [comment]
@SwConsults: First, I just want to confirm what you're seeing.

In Chrome 66 and 68 (current Canary), I see nothing in the unmodified sample app. This is true both in the stackblitz project, and if I download and run the Angular sample project locally. That seems odd to me.
I _can_ see the sample app in Safari 11.1.

Before proceeding further, can you confirm whether or not you can see the unmodified sample app run in Chrome? I want to pin down whether the problem is with Elix or with the sample app.

It'd also be useful to see what the modified Angular source looks like, e.g., in a fork of the stackblitz project above.

**Comment by SwCon** [comment]
here's a related thread on the same issue:
https://stackblitz.com/edit/angular-u2q42g?file=src%2Fapp%2Fhero-job-ad.component.ts
https://github.com/angular/angular/issues/24044

**Comment by JanMiksovsky** [comment]
I've posted a version of the Angular sample app that adds an Elix component: https://github.com/JanMiksovsky/dynamic-component-loader.

[app.module.ts](https://github.com/JanMiksovsky/dynamic-component-loader/blob/master/src/app/app.module.ts) includes two necessarily lines that both mention `CUSTOM_ELEMENTS_SCHEMA` to enable the use of custom elements.
[index.html](https://github.com/JanMiksovsky/dynamic-component-loader/blob/master/src/index.html) includes a script tag to load the Elix AutosizeTextarea component.
[app.component.ts](https://github.com/JanMiksovsky/dynamic-component-loader/blob/master/src/app/app.component.ts) includes the use of `elix-autosize-textarea` in the component template.

Running this locally shows both the Angular ad component and the Elix autosize textarea. Given this, I feel comfortable asserting that Elix components run in an Angular app as expected.

It's unclear why this doesn't work inside of StackBlitz. I suspect the problem may have to do with the use of `type="module"`, which StackBlitz may not yet support. I compiled a version of the Elix AutosizeTextarea component into a regular .js script file (not a module), and StackBlitz was able to consume that.

**Comment by JanMiksovsky** [comment]
FWIW, I've updated the Angular sample to show a more realistic use of Elix in an Angular project. The project now declares a dependency on the elix package, and the app.component.ts file now imports the component it wants to use. This allows the compiler to include the component in the build.

Since the original concern has now been addressed, I'm going to close this issue.
