### ISSUE TITLE
Question: By customizable web-components do you also mean that they can be styled/themed with external CSS

### ISSUE THREAD

**Issue by mrin9** [elix/elix#83]
I like your web components - they seem like un-styled and therefore not opinionated, which is great

would you like to clarify in the readme, a little bit on your vision of  styling them or theming them. 

Do you think, its a good idea, to give an option or make it easier to leak styles to the shadow DOM so that they can be styled with an external stylesheet, or do you have any other way to make it possible, 
I am sure there will be cases where others can consume these component as is without any change to its behavior but style them according to some corporate guidelines ?

**Comment by mrin9** [comment]
Thanks for the pointer to the blog.  
Is there any way I can influence all you great people to give a consideration to  ```custom-css-properties```.

**Comment by JanMiksovsky** [comment]
We're really waiting for [CSS Shadow Parts](https://tabatkins.github.io/specs/css-shadow-parts/) so we can do proper theming of our components.

CSS custom properties are, in our experience, too granular — it's not possible to predict which properties someone might want to style and which should therefore be exposed as custom properties. We're not opposed to using them in theory if there were focused cases in which they would be an appropriate solution.

In the meantime, we generally prefer to use the subclassing approach @robbear referenced above. In addition, we've found that [exposing subelements as customizable parameters](https://component.kitchen/blog/posts/customizing-custom-elements-with-custom-elements) addresses many of the use cases for CSS Shadow Parts.

We plan to expand our documentation for those approaches. Among other things, we're very interested in showing how Elix components can be themed for companies that want to express their visual design in customized web components. If you work for (or do work for) such an organization, we'd like to hear more about that work.

[BTW, I'll be traveling through Tuesday, and won't see replies until Wednesday.]

**Comment by JanMiksovsky** [comment]
@mrin9 Please let me know if I can help answer any questions about styling Elix components. At this point in time, styling components is a rather complex topic, so I'm happy to help give pointers in how to adapt the generic Elix components for corporate/branded use. Feel free to reach out to me at jan@component.kitchen if you'd like to go into more detail.

Beyond that, I don't know if there's more we can do at this point for this specific issue, so I'd like to close it if that's okay with you.

**Comment by mrin9** [comment]
@JanMiksovsky , thanks for coming back on this, I agree with you that ```custom-css-properties``` are too granular and CSS shadow parts are the way to go. I have tried customizing them by way of extending.

But, in the mean time while we wait for CSS shadow parts to get browser support, I still feel a lot of theming support can be achieved out of the box by using lets say by adding 15 or less ```custom-css-properties```. But then there may be a lot of code churn or breaking changes later, so i will leave that for you to decide whats best path for your framework.
At this point this is no more an issue for me, so closing it
