### ISSUE TITLE
Can we use it in react-project? 

### ISSUE THREAD

**Issue by collegeimprovements** [elix/elix#88]
How can we use this components in react project ? 
What are some of the best practices/guidelines that we should be following.

**Comment by JanMiksovsky** [comment]
Elix components are just web components, so to use them in React, you'll just need to:

1. Install `elix` as a dependency in `package.json`.

```
npm install --save elix
```

2. Include `import` statements for the components you want.

```js
import 'elix/src/Carousel.js';
```

3. Reference the components using their HTML tag name.

```jsx
render() {
  return        
    <elix-carousel>
      ... Content goes here ...
    </elix-carousel>;
}
```

The React docs contain a (tiny) bit of information on using web components in React: https://reactjs.org/docs/web-components.html.

**Comment by collegeimprovements** [comment]
Thanks a lot.

**Comment by JanMiksovsky** [comment]
Just wanted to follow up on this. Your question about using Elix in React inspired us to finally publish a simple project showing how to do that: https://github.com/elix/react-example.

Thanks for submitting the original question!
