### ISSUE TITLE
FilterComboBox overflow

### ISSUE THREAD

**Issue by Mottie** [elix/elix#89]
The dropdown container's height should be limited and allow scrolling. Right now it overflows the container:

![FilterComboBox](https://user-images.githubusercontent.com/136959/57143134-d0a30a00-6d83-11e9-9579-31208494909a.gif)

**Comment by JanMiksovsky** [comment]
Thanks for reporting this. This appears to be a regression. We'll investigate.

**Comment by JanMiksovsky** [comment]
This issue took a long to track down, but we believe we have a fix for it on master. We'll deploy the fix in the next release.

**Comment by JanMiksovsky** [comment]
This fix has been deployed in Elix 6.0.0.

You should now see the correct behavior on https://component.kitchen/elix/FilterComboBox, but please reopen if something still looks incorrect.
