### ISSUE TITLE
Feature Request: CRUD component

### ISSUE THREAD

**Issue by nileshtrivedi** [elix/elix#90]
It would be great to have a component that takes an array of objects, a JSON schema and some nested elements to produce a CRUD interface for that array, allowing the user to add, edit and delete items from the array.

See https://github.com/vaadin/vaadin-crud and https://github.com/mdn/web-components-examples/tree/master/editable-list for example.

**Comment by JanMiksovsky** [comment]
Good idea. I've added this to our [list of desired components](https://component.kitchen/elix/vision). The idea will appear there when we update our next site update, probably in a couple of weeks.

**Comment by wolframkriesing** [comment]
Is there a limit/rule to what size of components are suitable for elix? Is something like a crud component suitable? Where is the limit? I am just curious to understand, thanks.

**Comment by JanMiksovsky** [comment]
Our general rules are that components must be:
1. General purpose
2. Of interest to a wide range of apps
3. Already popular

With the case of a CRUD component, the question will come down to whether there's really something general-purpose we could do. My initial idea is that a CRUD component would be a fairly abstract meta-component that relied heavily on [element roles](https://component.kitchen/elix/customizing#element-roles) to define the actual UI. Such a component would need to be able to accommodate substantial variation in the way different apps want to expose CRUD operations in the UI. If supporting such variation is not possible, then the component isn't really general-purpose in nature, so we wouldn't pursue it.

Before tackling a CRUD component, we'd want to tackle more primitive data-driven list components first. E.g., start with something that can be given an array of data and will instantiate and manage elements that correspond to the array items. From there we might move on to virtual scrolling lists and lists with CRUD operations.

For now, it's hard to say whether such components will actually be possible to do in a general way. But I do think the idea is promising enough that we should track it on our list of desired components to explore.

**Comment by JanMiksovsky** [comment]
This is now listed on https://component.kitchen/elix/vision as "Editable list".

Many thanks for the idea. Now that we're tracking it, I'm going to go ahead and close this.
