### ISSUE TITLE
Bug when resolve dependencies

### ISSUE THREAD

**Issue by next-jimmycollazos** [elix/elix#93]
Hi
when i run `npm install` command; npm show me the next error message:
```sh
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/componentkitchen/sauce-test-runner.git
npm ERR!
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```
pleas; can you check the version name of resource `componentkitchen/sauce-test-runner`?

**Comment by robbear** [comment]
The resource repo was previously set as private and is now marked as public. Please give it another try.

**Comment by JanMiksovsky** [comment]
I've double-checked this on a clean install, and it does appear to be fixed.

@next-jimmycollazos I'm going to close this, but please reopen if you still run into issues. Thanks for reporting the problem.
